kind: ExportedServiceSet
apiVersion: federation.maistra.io/v1
metadata:
  name: prod-mesh
  namespace: stage-mesh
spec:
  exportRules:
  - type: NameSelector
    nameSelector:
      namespace: stage-bookinfo
      name: "*"